# -*- coding: utf-8 -*-
"""Streamlt.App

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bsx9f4KHXayRUV7uqf_M5VyB21zl5Efd
"""



# install Streamlit App
!pip install -q streamlit pyngrok

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# import numpy as np
# import pandas as pd
# import matplotlib.pyplot as plt
# 
# st.title("Tube Round Hole Calculator")
# 
# tube_od = st.number_input("Tube OD (mm)", value=50.0)
# hole_dia = st.number_input("Hole Diameter (mm)", value=10.0)
# home_x = st.number_input("Hole Center X Position (mm)", value=0.0)
# hole_rotation = st.number_input("Tube Rotation (deg)", value=0.0)
# num_points = st.slider("Number of Points", 8, 360, 36)
# 
# if hole_dia > tube_od:
#     st.error("Hole diameter cannot exceed tube OD")
#     st.stop()
# 
# R = tube_od / 2
# r = hole_dia / 2
# 
# t = np.linspace(0, 2*np.pi, num_points, endpoint=False)
# 
# X = home_x + r*np.cos(t)
# Y = r*np.sin(t)
# 
# C_relative = np.degrees(np.arcsin(Y/R))
# C = hole_rotation + C_relative
# 
# surface_y = R*np.radians(C_relative)
# 
# df = pd.DataFrame({
#     "Point": range(1, num_points+1),
#     "X (mm)": X,
#     "C (deg)": C
# })
# 
# st.subheader("Toolpath Coordinates")
# st.dataframe(df)
# 
# fig, ax = plt.subplots(figsize=(10,6))
# 
# ax.plot(
#     np.append(X, X[0]),
#     np.append(surface_y, surface_y[0]),
#     color="blue"
# )
# 
# ax.scatter(X, surface_y, color="red")
# 
# for i, (x, y) in enumerate(zip(X, surface_y), start=1):
#     ax.annotate(str(i), (x, y))
# 
# ax.set_xlabel("Laser X Position (mm)")
# ax.set_ylabel("Tube Surface Position")
# ax.grid(True)
# ax.axis("equal")
# 
# st.pyplot(fig)
# 
# csv = df.to_csv(index=False)
# 
# st.download_button(
#     "Download CSV",
#     csv,
#     file_name="toolpath.csv"
# )

#Start Streamlit
!streamlit run app.py &>/content/logs.txt &

#Create Public Link
from pyngrok import ngrok

# Get your authtoken from https://dashboard.ngrok.com/get-started/your-authtoken
# and replace 'YOUR_AUTHTOKEN' with your actual token.
ngrok.set_auth_token("2IvrAFXSmWSfxyKU4YHouv8gf6f_81kpJCdcLzXneujKyPMLP")

public_url = ngrok.connect(8501)
print(public_url)

from pyngrok import ngrok
import os

os.system("streamlit run app.py --server.port 8501 &")

url = ngrok.connect(8501)
print("Streamlit URL:", url)

"""# Git deployment"""

#Create a GitHub repository.
#Upload:
#app.py
#requirements.txt

#Example requirements.txt:

streamlit
numpy
pandas
matplotlib

# Go to
#https://share.streamlit.io

# Share, send users
#Laser Hole Calculator
#https://cab6-34-72-173-55.ngrok-free.app/